# Generated by Django 2.0.2 on 2018-03-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_code', models.CharField(max_length=50)),
                ('challenge_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('Past', 'Past')], default='Upcoming', max_length=20)),
            ],
        ),
    ]
