# Generated by Django 2.0.2 on 2018-04-02 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_code', models.CharField(max_length=50)),
                ('challenge_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('Past', 'Past')], default='Upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=50)),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_file_url', models.CharField(max_length=50)),
                ('in_practice', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=100)),
                ('challenge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contests.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('cpp', 'cpp'), ('c', 'c'), ('python', 'python')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compile Time Error', 'Compile Time Error'), ('Checking', 'Checking')], default='Checking', max_length=20)),
                ('source_file', models.FileField(upload_to='')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
