# Generated by Django 2.0.2 on 2018-03-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=50)),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_file_url', models.CharField(max_length=50)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Challenge')),
            ],
        ),
    ]
