# Generated by Django 2.0.2 on 2018-04-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20180402_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
