# Generated by Django 2.0.2 on 2018-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20180329_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='in_practice',
            field=models.BooleanField(default=False),
        ),
    ]
