# Generated by Django 2.0.2 on 2018-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20180402_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score_achieved',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
