# Generated by Django 2.0.2 on 2018-03-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contests', '0004_auto_20180329_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('cpp', 'cpp'), ('c', 'c'), ('python', 'python')], default=None, max_length=20)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compile Time Error', 'Compile Time Error'), ('Checking', 'Checking')], default=None, max_length=20)),
                ('source_file', models.FileField(upload_to='')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
