# Generated by Django 2.0.2 on 2018-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compile Time Error', 'Compile Time Error'), ('Checking', 'Checking')], default='Checking', max_length=20),
        ),
    ]
